spring.application.name=rent-car-backend

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/rentcar
spring.datasource.username=rentcar
spring.datasource.password=rentcar
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
